# 4.6 GPU计算

In [2]:
!nvidia-smi # 对Linux/macOS用户有效

'nvidia-smi' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [3]:
import torch
from torch import nn

print(torch.__version__)

1.3.1


## 4.6.1 计算设备

In [4]:
torch.cuda.is_available() # cuda是否可用

True

In [5]:
torch.cuda.device_count() # gpu数量

1

In [6]:
torch.cuda.current_device() # 当前设备索引, 从0开始

0

In [7]:
torch.cuda.get_device_name(0) # 返回gpu名字

'GeForce RTX 2060 SUPER'

## 4.6.2 `Tensor`的GPU计算

In [8]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [9]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
x.device

device(type='cuda', index=0)

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [12]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [13]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [14]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [15]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [16]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[0.6040],
        [0.6336]], device='cuda:0', grad_fn=<AddmmBackward>)